const express = require('express');
const cors = require('cors');
const app = express();
app.use((req, res, next) => {
    req.url = decodeURIComponent(req.url);
    next();
  });
  const actividadRoutes = require('./routes/actividad.routes.js');
  const actividadesEstructuraRoutes = require('./routes/actividadesEstructura.routes.js');
  const ctactividadesEstructuraRoutes = require('./routes/ctactividadesEstructura.routes.js');

  const ciudadRoutes = require('./routes/ciudad.routes.js');
  const conjuntoRoutes = require('./routes/conjunto.routes.js');
  const tipoEvaluacionRoutes = require('./routes/tipoEvaluacion.routes.js');
  const diseñoRoutes = require('./routes/diseño.routes.js');
  const empresaRoutes = require('./routes/empresa.routes.js');
  const etapaRoutes = require('./routes/etapa.routes.js');
  const estructuraRoutes = require('./routes/estructura.routes.js');
  const personaRoutes = require('./routes/persona.routes.js');
  const proyectoRoutes = require('./routes/proyecto.routes.js');
  const reporteRoutes = require('./routes/reporte.routes.js');
  const rolRoutes = require('./routes/rol.routes.js');
  const tipoActividadRoutes = require('./routes/tipoActividad.routes.js');
  const tipoEstructuraRoutes = require('./routes/tipoEstructura.routes.js');
  const tipoViviendaRoutes = require('./routes/tipoVivienda.routes.js');
  const ubicacionEstructuraRoutes = require('./routes/ubicacionEstructura.routes.js');
  const usuarioRoutes = require('./routes/usuario.routes.js');
  const resultadoRoutes = require('./routes/resultado.routes.js');
  const seccionRoutes = require('./routes/seccion.routes.js');

app.use(cors());
app.use(express.json());
app.use('/actividad', actividadRoutes);
app.use('/actividades-seccion', actividadesEstructuraRoutes);
app.use('/ctactividades-seccion', ctactividadesEstructuraRoutes);
app.use('/ciudad', ciudadRoutes);
app.use('/conjunto', conjuntoRoutes);
app.use('/diseño', diseñoRoutes);
app.use('/tipo-evaluacion', tipoEvaluacionRoutes);
app.use('/empresa', empresaRoutes);
app.use('/etapa', etapaRoutes);
app.use('/estructura', estructuraRoutes);
app.use('/persona', personaRoutes);
app.use('/proyecto', proyectoRoutes);
app.use('/reporte', reporteRoutes);
app.use('/rol', rolRoutes);
app.use('/tipo-actividad', tipoActividadRoutes);
app.use('/tipo-estructura', tipoEstructuraRoutes);
app.use('/tipo-vivienda', tipoViviendaRoutes);
app.use('/ubicacion-estructura', ubicacionEstructuraRoutes);
app.use('/usuario', usuarioRoutes);
app.use('/seccion', seccionRoutes);
app.use('/resultado', resultadoRoutes);
module.exports = app;
